### PR TITLE
Fixed precision issue at high progress rates

### LINKED ISSUE #10: time_per_step() should return f64, not Duration.
Currently, the `Estimate::time_per_step` returns `Duration`. This limits the precision and range that time per step can represent – `Duration` always stores multiples of nanosecods. Moreover, if your step takes less than nanosecond, time per step would be 0, and the ETA would be always 00:00:00. This is how I discovered the bug.

TLDR: Here is list of speeds that indicatif currently supports: :)
…, ¼GB/s, ⅓GB/s, ½GB/s, 1GB/s, ∞YB/s.

### PR DESCRIPTION
**Pull request by kayru**
Fixes #10. 

`Estimate::time_per_step()` returns a `Duration`, which has a limited precision of 1ns. Unfortunately, this makes it impossible to handle high progress rates (>1 billion items per second).

The proposed solution is to add `seconds_per_step()` and deprecate time_per_step() in a future release. This PR intentionally leaves the old APIs in place to preserve backwards compatibility.

### CODE REVIEW

File: src/utils.rs [hunk 1]
```diff
@@ -75,12 +75,18 @@ impl Estimate {
     }
 
     pub fn record_step(&mut self, value: u64) {
+        self.record_step_with_elapsed_time(value, self.start_time.elapsed())
+    }
+
+    /// This helper function takes an explicit elapsed duration so that it could also be used in
+    /// test code, which must be deterministic.
+    fn record_step_with_elapsed_time(&mut self, value: u64, elapsed: Duration) {
```
Comment (djc) [inline src/utils.rs:83]: Is there some way we can test this that does not depend on just extracting a single-caller method here?

File: src/state.rs [hunk 2]
```diff
@@ -84,16 +84,23 @@ impl ProgressState {
     }
 
     /// Return the current average time per step
+    #[allow(dead_code)] // Keep for API compatibility. Should deprecate.
```
Comment (djc) [inline src/state.rs:87]: I think I'd like to just keep this but also add some explanation to the docs here about the limitations of `Duration` resolution.

File: src/state.rs [hunk 3]
```diff
@@ -84,16 +84,23 @@ impl ProgressState {
...
     pub fn avg_time_per_step(&self) -> Duration {
-        self.est.time_per_step()
+        secs_to_duration(self.est.seconds_per_step())
+    }
+
+    /// Return the current average time in seconds per step.
```
Comment (djc) [inline src/state.rs:92]: Style nit: please strip the period from the first comment line (it's a sentence fragment, not a sentence), and add an empty line between the two lines.

**Review by djc — COMMENTED** [review]
Thank you for working on this!

File: src/state.rs (hunk 2 above)
Comment (kayru) [reply src/state.rs:87]: What might be a reason to keep Duration around? It might be a source of bugs for users of the crate, similar to the bugs this PR fixes.

File: src/utils.rs (hunk 1 above)
Comment (kayru) [reply src/utils.rs:83]: An alternative option that I have considered was to just add an current time Instant parameter to `record_step()` (instead of calling .elapsed() internally), however I have discarded that approach as it's changing the public API even more. I agree that single-caller helper is not ideal. It's a compromise between deterministic testability and public API churn.

Comment (djc) [reply src/utils.rs:83]: Actually, `Estimate` is not part of the public API at all, so I think we can just change whatever we like here.

File: src/state.rs (hunk 2 above)
Comment (djc) [reply src/state.rs]: I think that `Duration` as a type is easier to work with than a floating point type: it has a bunch of facilities that cover common use cases for dealing with durations, and it's more obvious to understand when you have it in your code. There are definitely use cases where the 1ns resolution is not an issue, so those users might like to get the more obvious type.

File: src/utils.rs (hunk 1 above)
Comment (kayru) [reply src/utils.rs:83]: Aha, ok. `pub`-s gave the impression that it is. I'll see what `record_step()` idea looks like.

Comment (kayru) [reply src/utils.rs]: Looks a bit neater. Also improved test_time_per_step() itself a little bit.

File: src/state.rs (hunk 2 above)
Comment (kayru) [reply src/state.rs]: I'm definitely not going to argue about this much further and it's not a hill I'm willing to die on, but it _seems_ that average time per step can very easily get <1ns when dealing with bytes. Surfacing this to the user of the library allows them to introduce a bug that won't be caught at compile time and may not even happen until their application runs on a sufficiently fast machine (i.e. reading files from SATA vs NVMe SSD or using 1 vs 10 GbE). I'll be happy with just the minimal fix that allows built-in estimates and draw rate throttling functionality to work in my application :)

File: src/utils.rs (hunk 1 above)
Comment (djc) [reply src/utils.rs]: Let's change `record_step` to take a `now: Instant` argument, instead.

**Comment by djc** [comment]
I've gone ahead and just merged this, will iterate a bit on it.

**Comment by kayru** [comment]
Yay, thank you! ❤️
